# docker-compose.override.yml
services:
  editor:
    profiles: [editor]           # <── makes it opt-in
    build: .
    command: npm run le -- --port 5174 --host 0.0.0.0
    ports: ["5174:5174"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules